### ISSUE TITLE
Fix icon for browser launch

### ISSUE THREAD

**Issue by Garbee** [snapcrafters/brave#11]
The icon doesn't show for the launched browser as [reported upstream](https://github.com/brave/browser-laptop/issues/13155) about the snap install. To fix this add `StartupWMClass=brave` to the desktop file entry.

**Comment by Lonniebiz** [comment]
This issue should be opened back up.

The Brave icon/launcher isn't showing in Ubuntu 16.04.5. Instead it shows a Question-Mark-Icon after installing via snap:
sudo snap install brave

Garbee's work-around works, but this is still an open bug because the user shouldn't have to do that. Such installation steps should happen automatically in the installer, right?

**Comment by Lonniebiz** [comment]
Here's a quick way to apply Garbee's icon-fix in Ubuntu 16.04.5. 

Run all of this like it is one long command:

`sudo rm /usr/share/applications/brave.desktop ; sudo touch /usr/share/applications/brave.desktop ; sudo bash -c 'echo "StartupWMClass=brave" > /usr/share/applications/brave.desktop'`

After this, try rebooting if its not immediately fixed.
