### ISSUE TITLE
No Microsoft (Core) Fonts support

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [snapcrafters/brave#5]
On Solus (distro) with "mscorefonts" successfully installed and able to be used in Firefox, sites like Google Docs do not show "Arial" or "Times New Roman," indicating the Brave snap is not able to find them.

I confirmed this by downloading the .bz2 version of 0.18.29 (same as current Snap) and noticed the text within the UI is much crisper than the Snap version. As expected, Google Docs successfully defaulted to Arial using the .bz2 version while no such option appears in the Snap.

**Comment by Ads20000** [comment]
[This will be fixed with the release of `snapd` 2.29](https://forum.snapcraft.io/t/ubuntu-desktop-team-priorities/1397/15) which [will be released 30th October](https://forum.snapcraft.io/t/the-snapd-roadmap/1973), you can install 2.29 from October 2nd using `sudo snap refresh core --beta` then from October 23rd using `sudo snap refresh core --candidate` (or just remain on the `beta` channel). You could also get the fix now with `sudo snap refresh core --edge`, you may end up breaking everything else or something but you can just refresh to another channel if that happens!

**Comment by flexiondotorg** [comment]
This is fixed now.
